baseURL = "https://maxxxxxx-x.github.io/"
languageCode = "en-us"
title = "V3RY G0OD B10G"
theme = "PaperMod"
buildDrafts = false 

[[menu.main]]
identifier="tags"
name="tags"
url="/tags"
weight=10

[[menu.main]]
identifier="categories"
name="Catergories"
url="/categories/"
weight=20


[[menu.main]]
identifier="archives"
name="Archives"
url="/archives/"
weight=30

[params.profileMode]

enabled=true
title="Blog work yes?"
subtitle="pls work me want to play siege"
imageUrl="img/AuraGX.jpg"
imageWidth=120
imageHeight=120
imageTitle="culprit"

[params]
ShowBreadCrumbs=true
ShowReadingTime=true
ShowShareButtons=true
ShowPostNavLinks=true

[params.cover]
linkFullImages=true